# Generated by Django 4.2.7 on 2024-01-19 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_promotion_remise'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.categorie'),
        ),
    ]
