# Generated by Django 4.2.7 on 2024-01-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_offre_is_active_alter_offre_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='capacite',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offre',
            name='lieu',
            field=models.CharField(default='', max_length=200),
        ),
    ]
