# Generated by Django 3.2.23 on 2024-02-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_customuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='nombre_personnes',
            field=models.IntegerField(default=1),
        ),
    ]
