# Generated by Django 3.2.23 on 2024-02-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_reservation_nombre_personnes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='prix',
            field=models.FloatField(default=1),
        ),
    ]
